insert into USUARIO (id, email, password, nombre, apellidos, admin, gestionado) values (1, 'admin@admin.com', 'admin', 'Luis Miguel', 'López Magaña', true, true);
insert into USUARIO (id, email, password, nombre, apellidos, admin, gestionado) values (2, 'usuario@usuario.com', '1234', 'Miguel', 'Campos Rivera', false, true);
insert into USUARIO (id, email, password, nombre, apellidos, admin, gestionado) values (3, 'kbramall0@nytimes.com', '6syZHFD', 'Kaine', 'Bramall', false, false);
insert into USUARIO (id, email, password, nombre, apellidos, admin, gestionado) values (4, 'jpetrus1@discovery.com', 'o5iJqjpXy6', 'Judon', 'Petrus', false, false);
insert into AULA (id, nombre) values (5, '1º DAM');
insert into AULA (id, nombre) values (6, '2º DAM');
insert into AULA (id, nombre) values (7, 'Biblioteca');
insert into AULA (id, nombre) values (8, 'Laboratorio');
insert into AULA (id, nombre) values (9, '1º AyF');
insert into AULA (id, nombre) values (10, '1º Comercio');
insert into RESERVA (id, hora, aula_id, usuario_id, fecha) values (11, 0, 5, 2 ,'2019-10-27');
insert into RESERVA (id, hora, aula_id, usuario_id, fecha) values (12, 5, 5, 2 ,'2019-10-27');
insert into RESERVA (id, hora, aula_id, usuario_id, fecha) values (13, 5, 6, 2 ,'2019-10-24');
insert into RESERVA (id, hora, aula_id, usuario_id, fecha) values (14, 4, 6, 3 ,'2019-10-27');
insert into RESERVA (id, hora, aula_id, usuario_id, fecha) values (15, 1, 7, 3 ,'2019-10-25');